### ISSUE TITLE
Random numbers showing up as extract names

### ISSUE THREAD

**Issue by souperneon** [mapzen/data-pages#231] opened 2016-08-05 15:46 UTC
Looking here: https://mapzen-odes-extracts-staging.herokuapp.com/odes/extracts/
![screen shot 2016-08-05 at 11 44 10 am](https://cloud.githubusercontent.com/assets/6125224/17442071/02fb6a98-5b02-11e6-9683-00eea59294e3.png)

(I remember editing the default names for some of them in the text box before creating the custom extract)

**Comment by migurski** [comment] 2016-08-05 17:54
What if you look at https://mapzen.com/data/metro-extracts-alt/odes/extracts/ ?

**Comment by souperneon** [comment] 2016-08-05 18:18
Still there but they might be the ones I made in staging. Also, that link doesn't have all the latest changes, right?
![screen shot 2016-08-05 at 2 17 32 pm](https://cloud.githubusercontent.com/assets/6125224/17446459/63a08526-5b17-11e6-9d57-d77a8c100c6a.png)

**Comment by migurski** [comment] 2016-08-05 21:49
This is due to our development process being spread across a few different instances of the database, so it's not a bug. Closing!

**Closed by migurski** 2016-08-05 21:49 UTC
Labels: bug
